"use client";
import { useEffect,useRef,useState } from "react";
import { BatteryCharging,Mic,RefreshCcw,Send,ShieldCheck,SunMedium,Trash2 } from "lucide-react";
import ChatMessage from "./components/ChatMessage";
import SessionControls from "./components/SessionControls";

type Entry={role:"user"|"assistant";content:string;memoryContext?:any[];explainTrace?:{referenced_memory_ids:string[];primary_influence_memory_id:string|null;confidence_tier_choice:string|null;counterfactual:string|null}};
const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL||"http://localhost:8000";
const ENTITY_ID=process.env.NEXT_PUBLIC_DEMO_ENTITY_ID||"demo-consumer-1";
const factText=(m:any)=>m?.content||m?.observation||m?.text;

export default function ChatPage(){
 const[sessionId,setSessionId]=useState<string|null>(null),[messages,setMessages]=useState<Entry[]>([]),[input,setInput]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null),[hydrated,setHydrated]=useState(false),[recording,setRecording]=useState(false);const recognition=useRef<any>(null);
 useEffect(()=>{const id=sessionStorage.getItem("volta_session_id"),raw=sessionStorage.getItem("volta_chat_messages");if(id)setSessionId(id);if(raw)try{setMessages(JSON.parse(raw))}catch(e){console.error("Error parsing saved messages",e)}setHydrated(true)},[]);
 useEffect(()=>{if(!hydrated)return;sessionId?sessionStorage.setItem("volta_session_id",sessionId):sessionStorage.removeItem("volta_session_id")},[sessionId,hydrated]);
 useEffect(()=>{if(!hydrated)return;messages.length?sessionStorage.setItem("volta_chat_messages",JSON.stringify(messages)):sessionStorage.removeItem("volta_chat_messages")},[messages,hydrated]);
 useEffect(()=>{const C=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!C)return;const r=new C();r.continuous=false;r.interimResults=false;r.onresult=(e:any)=>setInput(e.results[0][0].transcript);r.onerror=()=>setRecording(false);r.onend=()=>setRecording(false);recognition.current=r},[]);
 const speak=(text:string)=>{if(!window.speechSynthesis)return;const u=new SpeechSynthesisUtterance(text.replace(/[*#_]/g,"")),v=window.speechSynthesis.getVoices();u.voice=v.find(x=>x.lang==="en-ZA")||v.find(x=>x.lang.startsWith("en"))||v[0];window.speechSynthesis.speak(u)};
 const toggleRecording=()=>{if(!recognition.current){alert("Speech recognition is not supported in this browser. Try Chrome.");return}recording?recognition.current.stop():(recognition.current.start(),setRecording(true))};
 async function startSession(){setLoading(true);setError(null);try{const r=await fetch(`${API_BASE}/sessions?entity_id=${ENTITY_ID}`,{method:"POST"});if(!r.ok)throw new Error(await r.text());const d=await r.json(),hello="Welcome back. I’m Volta. I’ll use what you’ve already confirmed and show why it matters. What has changed since we last spoke?";setSessionId(d.session_id);setMessages([{role:"assistant",content:hello}]);speak(hello)}catch(e){setError(e instanceof Error?e.message:"Failed to start session")}finally{setLoading(false)}}
 async function sendMessage(){if(!sessionId||!input.trim())return;setLoading(true);setError(null);const text=input.trim();setInput("");setMessages(p=>[...p,{role:"user",content:text}]);try{const r=await fetch(`${API_BASE}/sessions/${sessionId}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text})});if(!r.ok)throw new Error(await r.text());const d=await r.json();setMessages(p=>[...p,{role:"assistant",content:d.reply,memoryContext:d.memory_context_used,explainTrace:d.explain_trace}]);speak(d.reply)}catch(e){setError(e instanceof Error?e.message:"Failed to send message")}finally{setLoading(false)}}
 async function endSession(){if(!sessionId)return;setLoading(true);setError(null);try{const r=await fetch(`${API_BASE}/sessions/${sessionId}/end`,{method:"POST"});if(!r.ok)throw new Error(await r.text());setSessionId(null)}catch(e){setError(e instanceof Error?e.message:"Failed to end session")}finally{setLoading(false)}}
 async function demo(path:string,label:string){if(path==="reset"&&!confirm("Clear all memory and chat history? This cannot be undone."))return;setLoading(true);setError(null);try{const r=await fetch(`${API_BASE}/entities/${ENTITY_ID}/${path}`,{method:"POST"});if(!r.ok)throw new Error(await r.text());setMessages([]);setSessionId(null);alert(label)}catch(e){setError(e instanceof Error?e.message:`Failed to ${path}`)}finally{setLoading(false)}}
 const memories=messages.flatMap(m=>Array.isArray(m.memoryContext)?m.memoryContext:[]),unique=memories.filter((m,i,a)=>factText(m)&&a.findIndex(x=>(x.memory_id||x.id||factText(x))===(m.memory_id||m.id||factText(m)))===i),superseded=unique.filter(m=>m.is_superseded);
 return <div className="page-wrap consultation-page">
  <section className="consult-hero"><div><p className="eyebrow">Persistent solar guidance</p><h1 className="display">Your home energy decision,<br/>with context intact.</h1><p>Volta remembers the facts you confirm, notices when they change, and shows the evidence behind every recommendation.</p></div><SessionControls sessionActive={!!sessionId} loading={loading} onStart={startSession} onEnd={endSession}/></section>
  {error&&<div className="error" role="alert">{error}</div>}
  <div className="workspace">
   <aside className="context-rail"><section className="panel profile-panel"><div className="section-head"><span className="icon-box"><BatteryCharging size={18}/></span><div><p className="eyebrow">Energy profile</p><h2>What Volta knows</h2></div></div><dl className="profile-list"><div><dt>Electricity bill</dt><dd>Needs confirmation</dd></div><div><dt>Backup priority</dt><dd>Needs confirmation</dd></div><div><dt>Roof & home</dt><dd>Needs confirmation</dd></div><div><dt>Last confirmed</dt><dd>{unique.length?"Available in consultation evidence":"No confirmed context loaded"}</dd></div></dl><p className="honesty-note"><ShieldCheck size={15}/> Unknown facts stay unknown until you confirm them.</p></section>
   <section className="card remembered"><div className="section-head compact"><SunMedium size={17}/><h2>What Volta remembers</h2></div>{unique.length?<ul>{unique.slice(0,4).map((m,i)=><li key={m.memory_id||m.id||i}>{factText(m)}{m.is_superseded&&<span className="superseded">Superseded</span>}</li>)}</ul>:<p>Start or resume a consultation to load the real context used in advice.</p>}{superseded.length>0&&<p className="changed-note">{superseded.length} prior {superseded.length===1?"fact was":"facts were"} superseded.</p>}</section>
   <details className="demo-tools"><summary>Demo controls</summary><div><button className="button button-danger" disabled={loading||!!sessionId} onClick={()=>demo("reset","Memory and chat history cleared.")}><Trash2 size={15}/> Reset</button><button className="button" disabled={loading||!!sessionId} onClick={()=>demo("reseed","Demo data seeded successfully.")}><RefreshCcw size={15}/> Re-seed</button></div></details></aside>
   <section className={`panel chat-panel ${!sessionId ? "chat-panel-ready" : ""}`}><header className="chat-head"><div><span className="pill"><span className="dot"/> {sessionId?"Consultation active":"Consultation workspace"}</span><h2>{sessionId?"Continue your consultation":"Ready when you are"}</h2><p>{sessionId?"Tell Volta what changed. Advice will include its supporting memory.":"Use the Start consultation action above when you are ready. Your conversation will open here."}</p></div></header>
   {sessionId&&<><div className="message-list" aria-live="polite">{messages.map((m,i)=><ChatMessage key={i}{...m}/>)}{loading&&<div className="thinking"><span className="spinner"/> Volta is checking your context…</div>}</div>
   <div className="composer"><button className={`voice-button ${recording?"recording":""}`} onClick={toggleRecording} disabled={loading} aria-label={recording?"Stop recording":"Start voice input"}><Mic size={19}/></button><label className="sr-only" htmlFor="message">Message Volta</label><input id="message" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.nativeEvent.isComposing&&e.keyCode!==229)sendMessage()}} placeholder="Something changed? Tell Volta." disabled={loading}/><button className="send-button" onClick={sendMessage} disabled={loading||!input.trim()} aria-label="Send message"><Send size={19}/></button></div></>}
   </section></div>
 </div>
}
