#!/usr/bin/env python3
"""Write the non-secret runtime configuration shipped with the static app.

The Next.js app is statically exported, so build-time environment variables are
not sufficient for a CDN deployment.  This script writes the one public value
the browser needs—the API Gateway origin—without placing credentials in the
bundle.  It intentionally rejects localhost and non-HTTPS origins in a
production release.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from urllib.parse import urlparse


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / "frontend" / "public" / "runtime-config.js"
LOCAL_HOSTS = {"localhost", "127.0.0.1", "0.0.0.0", "::1", "[::1]"}


def normalise_origin(value: str, label: str, production: bool) -> str:
    value = value.strip().rstrip("/")
    if not value:
        raise ValueError(f"{label} is required.")

    parsed = urlparse(value)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise ValueError(f"{label} must be an absolute http(s) origin, got {value!r}.")
    if parsed.path not in {"", "/"} or parsed.params or parsed.query or parsed.fragment:
        raise ValueError(f"{label} must not include a path, query, or fragment.")
    if production and parsed.scheme != "https":
        raise ValueError(f"{label} must use HTTPS for a production release.")
    if production and (parsed.hostname or "").lower() in LOCAL_HOSTS:
        raise ValueError(f"{label} must not point to localhost in a production release.")
    return value


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--api-base-url",
        default=os.environ.get("VOLTA_PUBLIC_API_BASE_URL")
        or os.environ.get("NEXT_PUBLIC_API_BASE_URL", ""),
        help="Public API Gateway origin. Defaults to VOLTA_PUBLIC_API_BASE_URL.",
    )
    parser.add_argument(
        "--app-origin",
        default=os.environ.get("VOLTA_PUBLIC_APP_ORIGIN", ""),
        help="Public OSS/CDN application origin. Defaults to VOLTA_PUBLIC_APP_ORIGIN.",
    )
    parser.add_argument(
        "--release",
        default=os.environ.get("GIT_COMMIT", "local"),
        help="Non-secret release identifier exposed for support diagnostics.",
    )
    parser.add_argument(
        "--csrf-cookie-name",
        default=os.environ.get("VOLTA_CSRF_COOKIE_NAME", "volta_csrf"),
        help="Public CSRF cookie name. This is an identifier, never a token.",
    )
    parser.add_argument(
        "--csrf-header-name",
        default=os.environ.get("VOLTA_CSRF_HEADER_NAME", "X-CSRF-Token"),
        help="Public CSRF request header name. This is an identifier, never a token.",
    )
    parser.add_argument(
        "--environment",
        default=os.environ.get("APP_ENV", "production"),
        choices=("development", "staging", "production"),
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    production = args.environment == "production"
    try:
        api_origin = normalise_origin(args.api_base_url, "api base URL", production)
        app_origin = normalise_origin(args.app_origin, "app origin", production)
    except ValueError as exc:
        print(f"Runtime configuration error: {exc}", file=sys.stderr)
        return 2

    config = {
        "apiBaseUrl": api_origin,
        "appOrigin": app_origin,
        "csrfCookieName": args.csrf_cookie_name.strip() or "volta_csrf",
        "csrfHeaderName": args.csrf_header_name.strip() or "X-CSRF-Token",
        "release": args.release.strip() or "unknown",
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        "/* Generated by scripts/write_runtime_config.py. Do not add secrets. */\n"
        f"window.__VOLTA_RUNTIME_CONFIG__ = Object.freeze({json.dumps(config, separators=(',', ':'))});\n",
        encoding="utf-8",
    )
    print(f"Wrote public runtime config to {args.output} for {api_origin}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
